### ISSUE TITLE
Rework for multiple shift start dates

### ISSUE THREAD

**Issue by chopchop505** [StatEngine/shiftly#13]
I would like to refactor some of the logic you added, if possible without breaking existing tests and API. Let me know your thoughts.
The goal is to keep all the complexity of shifts within shiftly.  Shiftly clients shouldn't need to keep track of multiple configs, calculate start dates, etc.

Can we change the ShiftConfiguration constructor to except one argument, either an array or a single object:
```
export function CarmelIN() {
  return [new ShiftConfiguration([{
    firstDay: '2019-01-01',
    pattern: 'abacacbcb',
    shiftStart: '0800',
    timeZone: 'US/Eastern',
  }, {
    firstDay: '2018-01-01',
    pattern: 'abcbcacab',
    shiftStart: '0800',
    timeZone: 'US/Eastern',
  }])
```

Then the utility functions, `calculateShift`, `shiftTimeFrame` would need to determine which start date to use.

The client could then use, without even caring about the different start dates.  
```
const ShiftConfiguration = FirecaresLookup['76662']
const shiftly = new ShiftConfiguration();
shiftly.calculateShift('2014-09-08T08:02:17-05:00')
```

**Comment by JWileczek** [comment]
Can do, I was considering refactoring that way initially but it was a larger refactor that would've taken longer so I figured moving to it in steps would be appropriate. I already have a branch half-way to what you are describing really locally so I'll just update and extend from there.

@garnertb @chopchop505 One question it would be good to nail down while we are doing this refactor is how we handle dates outside of any shift configuration we have? I see the current implementation is to reverse the pattern and calculate against that? I guess I'm confused at how that works if someone could explain it because in my mind it would make more sense just to not calculate a shift in that case since we can't be sure the pattern would be correct?
